from .base_query_augmentation import PassQueryAugmentation
from .synonym_extension_qa import SynonymExtensionQueryAugmentation
from .rewriting_query_augmentation import RewritingQueryAugmentation
from .normalization_query_augmentation import NormalizeQueryAugmentation